crud/crud/urls.py
from django.contrib import admin
from django.urls import path
from customer import views

urlpatterns = [
    path('', views.readCustomer),
    path('create', views.createCustomer),
    path('edit/<int:id>', views.editCustomer),
    path('update/<int:id>', views.updateCustomer),
    path('delete/<int:id>', views.destroyCustomer),
    path('admin/', admin.site.urls),
]

crud/customer/models.py
from random import choices
from django.conf import settings
from django.db import models

class Customer(models.Model):
    cid = models.CharField(max_length=11)
    cname = models.CharField(max_length=100)  
    csurname = models.CharField(max_length=100)
    cphone = models.CharField(max_length=100)
    ccity = models.CharField(max_length=100)
    cdistrict = models.CharField(max_length=100)

    class Meta:  
        db_table = "customer"

crud/customer/forms.py
from django import forms  
from customer.models import Customer

class CustomerForm(forms.ModelForm):  
    class Meta:  
        model = Customer  
        fields = "__all__"  

crud/customer/views.py
from django.shortcuts import render, redirect  
from customer.forms import CustomerForm  
from customer.models import Customer

def createCustomer(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)  
        if form.is_valid():  
            try:
                form.save()  
                return redirect(readCustomer)  
            except:  
                pass
    else:
        form = CustomerForm()  
    return render(request,"create.html", {'form':form})

def readCustomer(request):
    customers = Customer.objects.all().order_by('-id')
    return render(request,"read.html", {'customers':customers})

def editCustomer(request, id):
    customer = Customer.objects.get(id=id)  
    return render(request,'update.html', {'customer':customer})

def updateCustomer(request, id):
    customer = Customer.objects.get(id=id)  
    form = CustomerForm(request.POST, instance = customer)  
    if form.is_valid():
        form.save()
        return redirect(readCustomer)  
    return render(request, 'update.html', {'customer': customer})

def destroyCustomer(request, id):
    customer = Customer.objects.get(id=id)  
    customer.delete()  
    return redirect(readCustomer)

crud/customer/templates/create.html
<!DOCTYPE html>  
<html lang="en">
    <head>  
        <meta charset="UTF-8">  
        <title>customerCRUD | Add Customer</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            body {
                text-align: center;
            }
            form {
                display: inline-block;
            }
        </style>
    </head>
    <body style="text-decoration-color: #0068f4">
        <form method="POST" class="post-form" action="/create">
            {% csrf_token %}
            <div class="container">
            {% load static %}
                <img src="{% static '/images/logo.png' %}" alt="Logo" width="400">
                <br>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <h3>Add Info    </h3>
                    </div>  
                    <label class="col-sm-2 col-form-label">ID:</label>  
                    <div class="col-sm-4">  
                        {{ form.cid }}
                    </div>  
                </div>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Name:</label>  
                    <div class="col-sm-4">  
                        {{ form.cname }}
                    </div>  
                
                    <label class="col-sm-2 col-form-label">Surname:</label>  
                    <div class="col-sm-4">  
                        {{ form.csurname }}
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">City:</label>  
                    <div class="col-sm-4">  
                        {{ form.ccity }}
                    </div>  
                    <label class="col-sm-2 col-form-label">District:</label>  
                    <div class="col-sm-4">  
                        {{ form.cdistrict }}
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Phone:</label>  
                    <div class="col-sm-4">  
                        {{ form.cphone }}
                    </div>  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <button type="submit" class="btn btn-primary" style="width: -webkit-fill-available;">Submit</button>  
                    </div>  
                </div>  
            </div>  
        </form>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>  
</html>

crud/customer/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            text-align: center;
        }
        form {
            display: inline-block;
        }
    </style>
</head>  
    <body>  
        <form method="POST" class="post-form" action="/update/{{customer.id}}">  
                {% csrf_token %}  
            <div class="container">
            {% load static %}
            <img src="{% static '/images/logo.png' %}" alt="Logo" width="400">  
            <br>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <h3>Edit Details</h3> 
                    </div>
                    <label class="col-sm-2 col-form-label">ID:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cid" id="id_cid" required maxlength="20" value="{{ customer.cid }}"/>  
                    </div>  
                </div>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Name:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cname" id="id_cname" required maxlength="100" value="{{ customer.cname }}" />  
                    </div> 
                    <label class="col-sm-2 col-form-label">Surname:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="csurname" id="id_csurname" required maxlength="100" value="{{ customer.csurname }}" />  
                    </div>  
                </div>
                
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">City:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="ccity" id="id_ccity" required maxlength="100" value="{{ customer.ccity }}" />  
                    </div>  
                    <label class="col-sm-2 col-form-label">District:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cdistrict" id="id_cdistrict" required maxlength="100" value="{{ customer.cdistrict }}" />  
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Phone:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cphone" id="id_cphone" required maxlength="100" value="{{ customer.cphone }}" />  
                    </div>  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <button type="submit" class="btn btn-success" style="width: -webkit-fill-available;">Update</button>  
                    </div>  
                </div>  
            </div>  
        </form>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>  
</html> 

crud/customer/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <style>
            body {
                text-align: center;
            }
            form {
                display: inline-block;
            }
        </style>
    </head>
    <body style="text-decoration-color: #0068f4">
        <form method="POST" class="post-form" action="/add">
            {% csrf_token %}
            <div class="container">
            {% load static %}
                <img src="{% static '/images/logo.png' %}" alt="Logo" width="400">
                <br>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <h3>Enter Details</h3>
                    </div>  
                    <label class="col-sm-2 col-form-label">ID:</label>  
                    <div class="col-sm-4">  
                        {{ form.cid }}
                    </div>  
                </div>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Name:</label>  
                    <div class="col-sm-4">  
                        {{ form.cname }}
                    </div>  
                
                    <label class="col-sm-2 col-form-label">Surname:</label>  
                    <div class="col-sm-4">  
                        {{ form.csurname }}
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">City:</label>  
                    <div class="col-sm-4">  
                        {{ form.ccity }}
                    </div>  
                    <label class="col-sm-2 col-form-label">District:</label>  
                    <div class="col-sm-4">  
                        {{ form.cdistrict }}
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Phone:</label>  
                    <div class="col-sm-4">  
                        {{ form.cphone }}
                    </div>  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <button type="submit" class="btn btn-primary" style="width: -webkit-fill-available;">Submit</button>  
                    </div>  
                </div>  
            </div>  
        </form>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>  
</html>

crud/customer/templates/read.html
<!DOCTYPE html>  
<html lang="en">  
    <head>
        {% load static %}
        <meta charset="UTF-8">  
        <title>customerCRUD | Customers</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <style>
            a {
                text-decoration:none
            }
        </style>
    </head>  
    <body>
            {% load static %}
            <img src="{% static '/images/logo.png' %}" alt="Logo" width="200">
            <a href="/create" class="btn btn-primary">Add Customer</a>
        <table class="table table-striped table-bordered table-sm">  
            <thead class="thead-dark">  
                <tr>  
                    <th>Customer ID</th>  
                    <th>Customer Name</th>  
                    <th>Customer Surname</th>  
                    <th>Customer Phone</th>
                    <th>Customer City</th>
                    <th>Customer District</th>
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                {% for customer in customers %}  
                <tr>  
                    <td>{{ customer.cid }}</td>
                    <td>{{ customer.cname }}</td>
                    <td>{{ customer.csurname }}</td>
                    <td>{{ customer.cphone }}</td>
                    <td>{{ customer.ccity }}</td>
                    <td>{{ customer.cdistrict }}</td>
                    <td>
                        <a href="/update/{{ customer.id }}"><i class="fa-solid fa-square-pen text-success"></i><span class="text-success">Edit</span></a>
                            &nbsp;
                        <a href="/delete/{{ customer.id }}"><i class="fa-solid fa-trash text-danger"></i><span class="text-danger">Delete</span></a>
                    </td>  
                </tr>
                {% endfor %}  
            </tbody>  
        </table>  
        <br><br>  

        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>
</html>  

crud/customer/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
    <head>
        {% load static %}
        <meta charset="UTF-8">  
        <title>Customers</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <style>
            a {
                text-decoration:none
            }
        </style>
    </head>  
    <body>
            {% load static %}
            <img src="{% static '/images/logo.png' %}" alt="Logo" width="200">
            <a href="/add" class="btn btn-primary">Add New Customer</a>
        <table class="table table-striped table-bordered table-sm">  
            <thead class="thead-dark">  
                <tr>  
                    <th>Customer ID</th>  
                    <th>Customer Name</th>  
                    <th>Customer Surname</th>  
                    <th>Customer Phone</th>
                    <th>Customer City</th>
                    <th>Customer District</th>
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                {% for customer in customers %}  
                <tr>  
                    <td>{{ customer.cid }}</td>
                    <td>{{ customer.cname }}</td>
                    <td>{{ customer.csurname }}</td>
                    <td>{{ customer.cphone }}</td>
                    <td>{{ customer.ccity }}</td>
                    <td>{{ customer.cdistrict }}</td>
                    <td>
                        <a href="/edit/{{ customer.id }}"><i class="fa-solid fa-square-pen text-success"></i><span class="text-success">Edit</span></a>
                            &nbsp;
                        <a href="/delete/{{ customer.id }}"><i class="fa-solid fa-trash text-danger"></i><span class="text-danger">Delete</span></a>
                    </td>  
                </tr>
                {% endfor %}  
            </tbody>  
        </table>  
        <br><br>  

        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>
</html>  

crud/customer/templates/update.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>customerCRUD | Edit Customer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            text-align: center;
        }
        form {
            display: inline-block;
        }
    </style>
</head>  
    <body>  
        <form method="POST" class="post-form" action="/update/{{customer.id}}">  
                {% csrf_token %}  
            <div class="container">
            {% load static %}
            <img src="{% static '/images/logo.png' %}" alt="Logo" width="400">  
            <br>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <h3>Edit Details</h3> 
                    </div>
                    <label class="col-sm-2 col-form-label">ID:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cid" id="id_cid" required maxlength="20" value="{{ customer.cid }}"/>  
                    </div>  
                </div>  
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Name:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cname" id="id_cname" required maxlength="100" value="{{ customer.cname }}" />  
                    </div> 
                    <label class="col-sm-2 col-form-label">Surname:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="csurname" id="id_csurname" required maxlength="100" value="{{ customer.csurname }}" />  
                    </div>  
                </div>
                
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">City:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="ccity" id="id_ccity" required maxlength="100" value="{{ customer.ccity }}" />  
                    </div>  
                    <label class="col-sm-2 col-form-label">District:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cdistrict" id="id_cdistrict" required maxlength="100" value="{{ customer.cdistrict }}" />  
                    </div>  
                </div>
                <div class="form-group row">  
                    <label class="col-sm-2 col-form-label">Phone:</label>  
                    <div class="col-sm-4">  
                        <input type="text" name="cphone" id="id_cphone" required maxlength="100" value="{{ customer.cphone }}" />  
                    </div>  
                    <label class="col-sm-2 col-form-label"></label>  
                    <div class="col-sm-4">  
                        <button type="submit" class="btn btn-success" style="width: -webkit-fill-available;">Update</button>  
                    </div>  
                </div>  
            </div>  
        </form>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js" integrity="sha512-8cU710tp3iH9RniUh6fq5zJsGnjLzOWLWdZqBMLtqaoZUA6AWIE34lwMB3ipUNiTBP5jEZKY95SfbNnQ8cCKvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>  
</html> 